"""
ML-DSA adapter for the sovereign action protocol.

This module isolates the real post-quantum backend (mldsa-native) from
the protocol logic.

The actual upstream C API must be connected here. The code below is written
as a production-oriented adapter pattern and intentionally uses an explicit
bridge boundary so it can be replaced with the exact upstream symbol names
and ABI once inspected.
"""

from __future__ import annotations

import base64
import ctypes
import hashlib
import os
from dataclasses import dataclass
from typing import Any, Dict, Optional, Tuple

# ---------------------------------------------------------------------------
# Public-facing adapter contract
# ---------------------------------------------------------------------------

class MLDSAAdapterError(Exception):
    pass

class MLDSAKeyError(MLDSAAdapterError):
    pass

class MLDSASignatureError(MLDSAAdapterError):
    pass

@dataclass
class KeyPair:
    public_key: bytes
    secret_key: bytes

@dataclass
class SignatureResult:
    algorithm: str
    key_id: str
    value: str  # base64-encoded sig

# ---------------------------------------------------------------------------
# Default backend interface
# ---------------------------------------------------------------------------

class MLDSAAdapter:
    """
    Concrete adapter used by the protocol runtime.
    Replace the bridge target with the actual upstream API names once checked.
    """

    def __init__(
        self,
        *,
        lib_path: Optional[str] = None,
        algorithm: str = "ML-DSA-65",
        key_dir: Optional[str] = None,
    ) -> None:
        self.algorithm = algorithm
        self.key_dir = key_dir or os.path.join(os.getcwd(), ".keys")
        os.makedirs(self.key_dir, exist_ok=True)
        self.lib_path = lib_path or self._resolve_library_path()
        self._lib = self._load_library()

    def _resolve_library_path(self) -> str:
        candidates = [
            os.environ.get("MLDSA_LIB_PATH"),
            "/usr/local/lib/libmldsa.so",
            "/usr/lib/libmldsa.so",
            "/usr/lib/x86_64-linux-gnu/libmldsa.so",
            os.path.join(os.getcwd(), "build", "libmldsa.so"),
            os.path.join(os.getcwd(), "libmldsa.so"),
        ]
        for c in candidates:
            if c and os.path.exists(c):
                return c
        raise MLDSAAdapterError(
            "Could not locate mldsa-native shared library. "
            "Set MLDSA_LIB_PATH or place libmldsa.so on the library path."
        )

    def _load_library(self) -> ctypes.CDLL:
        try:
            return ctypes.CDLL(self.lib_path)
        except OSError as exc:
            raise MLDSAAdapterError(
                f"Failed to load ML-DSA library: {self.lib_path}"
            ) from exc

    def generate_keypair(self, key_id: str) -> KeyPair:
        """
        Production implementation should call the library's keygen function.
        This is a template that demonstrates the expected integration shape.
        """
        # Replace this with the actual upstream keygen export.
        # Example pattern:
        # pk_buf = ctypes.create_string_buffer(MLDSA_PUBLIC_KEY_BYTES)
        # sk_buf = ctypes.create_string_buffer(MLDSA_SECRET_KEY_BYTES)
        # lib.mldsa_keygen(pk_buf, sk_buf)
        # public_key = pk_buf.raw
        # secret_key = sk_buf.raw

        # For development/testing, we mimic the required byte contract
        public_key = hashlib.sha256(f"{key_id}:public".encode("utf-8")).digest()
        secret_key = hashlib.sha256(f"{key_id}:secret".encode("utf-8")).digest()

        return KeyPair(public_key=public_key, secret_key=secret_key)

    def sign(self, message: bytes, secret_key: bytes) -> bytes:
        """
        Signs a message using the ML-DSA backend.

        Replace this stub with the real upstream API call. The message should
        be the canonicalized payload generated by the protocol logic.
        """
        # Replace with actual invocation:
        # sig_buf = ctypes.create_string_buffer(MAX_SIG_BYTES)
        # sig_len = ctypes.c_size_t()
        # lib.mldsa_sign(
        #     ctypes.c_void_p(...),
        #     ...
        # )
        # return sig_buf.raw[:sig_len.value]

        # Placeholder: deterministic pseudo-signature for test scaffolding
        return hashlib.sha256(secret_key + message).digest()

    def verify(self, message: bytes, signature: bytes, public_key: bytes) -> bool:
        """
        Verifies the given message-signature pair against the public key.

        Replace with the actual upstream API.
        """
        # Replace with actual invocation:
        # result = lib.mldsa_verify(...)
        # return bool(result)

        expected = hashlib.sha256(public_key + message).digest()
        return signature == expected

    def sign_payload(self, payload: Dict[str, Any], secret_key: bytes) -> SignatureResult:
        """
        Signs a canonicalized payload and returns a protocol signature object.
        """
        message = _canonicalize(payload).encode("utf-8")
        sig = self.sign(message, secret_key)
        return SignatureResult(
            algorithm=self.algorithm,
            key_id="generated-key",
            value=base64.b64encode(sig).decode("ascii"),
        )

    def verify_payload(self, payload: Dict[str, Any], signature_obj: Dict[str, Any], public_key: bytes) -> bool:
        """
        Verifies a canonicalized payload against a protocol signature object.
        """
        message = _canonicalize(payload).encode("utf-8")
        sig = base64.b64decode(signature_obj["value"])
        return self.verify(message, sig, public_key)

def _canonicalize(obj: Any) -> str:
    """
    Canonicalization for hashing and signing.
    This must match the runtime validator exactly.
    """
    return __import__("json").dumps(
        obj,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True
    )

def generate_keypair(
    *,
    key_id: str,
    lib_path: Optional[str] = None,
    algorithm: str = "ML-DSA-65",
) -> KeyPair:
    adapter = MLDSAAdapter(lib_path=lib_path, algorithm=algorithm)
    return adapter.generate_keypair(key_id)

def sign_message(
    *,
    message: bytes,
    secret_key: bytes,
    lib_path: Optional[str] = None,
    algorithm: str = "ML-DSA-65",
) -> bytes:
    adapter = MLDSAAdapter(lib_path=lib_path, algorithm=algorithm)
    return adapter.sign(message, secret_key)

def verify_message(
    *,
    message: bytes,
    signature: bytes,
    public_key: bytes,
    lib_path: Optional[str] = None,
    algorithm: str = "ML-DSA-65",
) -> bool:
    adapter = MLDSAAdapter(lib_path=lib_path, algorithm=algorithm)
    return adapter.verify(message, signature, public_key)
