[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
pythonpath = . backend
norecursedirs = .git .tox dist build *.egg external
markers =
    asyncio: mark a test as an asyncio coroutine
asyncio_mode = auto
