# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: Swift-project

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Build
        run: |
          swift build -v
      - name: Run tests
        run: |
          swift test -v
