name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build Swift v6.4
      shell: bash
      run: |
       swift build -v
    - name: Run tests Swift v6.4
      run: |
       swift test -v
